spring.application.name=taskmanager
spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager_db
spring.datasource.username=marco
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect